services:
  db:
    container_name: subsquid_db
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - '${DB_PORT}:5432'
      # command: ["postgres", "-c", "log_statement=all"]
    # volumes:
    # - ./assets/${CHAIN}/init.sql:/docker-entrypoint-initdb.d/init.sql
  #      - ./data/db:/var/lib/postgresql/data
  api:
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - '4350:4350'
    command: ['sqd', 'serve:prod']
    depends_on:
      db:
        condition: service_healthy
  processor:
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      # any other variables that your squid processor may be using
    ports:
      # prometheus metrics exposed at port 3000
      - '3000:3000'
    command: ['sqd', 'process:prod']
    depends_on:
      db:
        condition: service_healthy
