services:
  db:
    container_name: subsquid_db
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d squid"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    command: ["npm", "run", "db:migrate"]
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      migrator:
        condition: service_completed_successfully

  processor:
    build: .
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      migrator:
        condition: service_completed_successfully
